version: ~> 1.0

os: windows
language: shell

env:
  global:
    - secure: p9HMcLujuqXNO+TNLcCxrcMj8yzCRmtTTQHksTPw6kc8YdvYDvxOQ6Ngeo+VXTJQTKSh1D5bDuFF3m+ZoOl4vY8TyVIlNtKaM2TtJy1zsXgRVTSkO6yO2AZ4McFBN/lC/ODXD5aRCOjRmygYcRIca5Lw/8xUprf2h8kVFmPkrwQfSn1Fdz7Jt4DuEao3m7iHfya+1YD1+iB9JfDVE40NmDmwt3POJ+HjCOzDYXU0e9FCI3ZIIern23kMPFVhVoge2DX2kPf3ygTKjgZVUCDxQvKrN8qIvBe8I3Z7fhG1yQHPwsFkWWaj27aKmCpiVW5RQoY55KHALCWRDUGoGzO7xkvcXqiyz/OXpyP3RA6v4J0B7V5ChdjPM/Cv8a29imMHUKUV6GEUXcKP0J3JxeHmSarmh+zp+xvw6DCWXPmFvTEh62Mx1nvny/t6FFaUebWBg/upWen4ecIY/x3oy0l+40a8DOmFMA1EwxdY8e4RnYA0lnQ4Mr4MKvV1oA6bz4wfYh0cLsnmQZO4BgqQfgH/wqXX8fNiwxxKDv1JPKZBtQREnu7hq6gxDz8jQXHVZrxZd3D4n7hPHThxUUuQE7gYqjzMcY2iZL7V8tNzhqqcCPHlLT44frF7drs+9UM83HQB6nn9c82798VjgdsNt7AzB/uT0vI9JsyrKt9f9lP3Ic0= # GITHUB_TOKEN

import:
  - source: portapps/portapps:.travis/configs/install.yml
  - source: portapps/portapps:.travis/configs/build.yml
  - source: portapps/portapps:.travis/configs/set-version.yml
  - source: portapps/portapps:.travis/configs/git-config.yml
  - source: portapps/portapps:.travis/configs/deploy.yml
  - source: portapps/portapps:.travis/configs/notifs.yml
