version: ~> 1.0

os: windows
language: shell

import:
  - source: portapps/portapps:.travis/configs/install.yml
  - source: portapps/portapps:.travis/configs/build.yml
  - source: portapps/portapps:.travis/configs/set-version.yml
  - source: portapps/portapps:.travis/configs/git-config.yml
  - source: portapps/portapps:.travis/configs/deploy.yml
  - source: portapps/portapps:.travis/configs/notifs.yml

deploy:
  api_key:
    secure: fXmrnF+rhmRkW4BghWaTy26RJtVqyKYu5rzh82aD2aoV9JsdSbr07qc77EPuuUdKwX1iz+HNOgoZuwA7vw08HnE8H65UPyYgRF5wJrdWMNzrvGJhIfrvnI78OKdgtW2SEoIr/mYf2NMP4PI+7CskYpLVFhqrSP9tkYVoQqsovmRDCzZjAHHkMLxGNL6Ap/vryHjaNLJmun427jBOX8BJPx5vY4BJJ23w4B2ZwJvvwtETphhSz+Z5MA2/Q0NslhSaAY/rQ6XciY53A1R9Xr1hLmFArq9UOgmDzpRWUA73xc4bde/EtYKowu2eJK/FzA7Q/mHG7a1i8cSHZddQN7v22uNu4fJxXRcI373/tvD40FYiXkgE2SK4AJZxcMFyvFKc8qx4Hy0USLR1Azx8/kMV6cfPVbEGqkqCtvBV3+++pQX1+9B0cI4ixyWDT/WRz7/8K8laJ1fSlcP2+mxOG9Uhc2trBf2t0MfOZoQeaCyKo5RPzppK7Nbwi8JdvSNsGAkxm7fJ40y5saJKTk3Arq9NMj5qtRI3eT7RIDEsDrHJ2yLXqIEukrgyZgwLfBNOb82LRg0yj3+rVV+KrnHi8lxNxIr8dWNXeL2bSo3RZ1nbext8x0XGbG64Px96b0hNav8DAinv0x/fVOkuVQC6kUfCY1DI4TPJgFMbRCUfhZcs2cw=
